#!/usr/bin/env python3

import re
from gradelib import *

r = Runner(save("xv6.out"))


@test(1, "[MANDATORY] schedls reports two schedulers")
def test1():
    r.run_qemu(shell_script(["schedls"]))
    r.match(
        "\[ \]\tScheduler Name\tScheduler ID",
        "====================================",
        "\[\*\]\tRound Robin\t1",
        "   \t[a-zA-Z0-9_ ]+\t2",
    )


@test(1, "[MANDATORY] schedset changes scheduler")
def test2():
    r.run_qemu(shell_script(["schedset 2", "echo OK"]), timeout=5)
    r.match("^OK$", "^Scheduler successfully changed to [a-zA-Z0-9_ ]+$")


@test(1, "[MANDATORY] complete benchmark after scheduler switch")
def test3():
    r.run_qemu(
        shell_script(["schedset 2", "sh load.sh", "echo OK"]), timeout=5
    )
    r.match(
        "^Scheduler successfully changed to [a-zA-Z0-9_ ]+$",
        "[0-9]+\s+[0-9]+\s+[0-9]+",
        "^OK$",
    )


@test(1, "[MANDATORY] time benchmark complete after scheduler switch")
def test4():
    r.run_qemu(
        shell_script(["schedset 2", "time sh load.sh", "echo OK"]),
        timeout=5,
    )
    r.match(
        "^Scheduler successfully changed to [a-zA-Z0-9_ ]+$",
        "[0-9]+\s+[0-9]+\s+[0-9]+",
        "Executing sh took [0-9]+ ticks",
        "^OK$",
    )


@test(0, "[OPTIONAL] optimized scheduler added")
def test5():
    r.run_qemu(shell_script(["schedls"]))
    r.match(
        "\[ \]\tScheduler Name\tScheduler ID",
        "====================================",
        "\[\*\]\tRound Robin\t1",
        "   \t[a-zA-Z0-9_ ]+\t2",
        "   \t[a-zA-Z0-9_ ]+\t3",
    )


@test(0, "[OPTIONAL] optimized scheduler runs benchmark with time")
def test6():
    r.run_qemu(
        shell_script(["schedset 3", "time sh load.sh", "echo OK"]),
        timeout=5,
    )
    r.match(
        "^Scheduler successfully changed to [a-zA-Z0-9_ ]+$",
        "[0-9]+\s+[0-9]+\s+[0-9]+",
        "Executing sh took [0-9]+ ticks",
        "^OK$",
    )


run_tests()
